#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# BlackNode Sentinel — One-Command Deployment Script
# ──────────────────────────────────────────────────────────────
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# ── Helper Functions ──────────────────────────────────────────
info()    { echo -e "${BLUE}[INFO]${NC}  $1"; }
success() { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Banner ────────────────────────────────────────────────────
echo -e "${CYAN}"
echo "  ╔═══════════════════════════════════════════════════════╗"
echo "  ║        🛡️  BlackNode Sentinel — Deployer            ║"
echo "  ║        Runtime Application Self-Protection           ║"
echo "  ╚═══════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Step 1: Check Docker & Docker Compose ─────────────────────
info "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker: https://docs.docker.com/get-docker/"
fi
success "Docker found: $(docker --version)"

# Check for docker compose (v2 plugin) or docker-compose (standalone)
COMPOSE_CMD=""
if docker compose version &> /dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
    success "Docker Compose found: $(docker compose version --short 2>/dev/null || echo 'v2+')"
elif command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
    success "Docker Compose (standalone) found: $(docker-compose --version)"
else
    error "Docker Compose is not installed. Please install Docker Compose."
fi

# ── Step 2: Generate .env File ────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    warn ".env file already exists. Backing up to .env.bak"
    cp "$ENV_FILE" "$ENV_FILE.bak"
fi

info "Generating .env file with secure defaults..."

# Generate random secrets
JWT_SECRET=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)
MONGO_ROOT_PASS=$(head -c 16 /dev/urandom | base64 | tr -d '/+=' | head -c 16)

cat > "$ENV_FILE" << EOF
# ── BlackNode Sentinel — Environment Configuration ──────────
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── MongoDB ──────────────────────────────────────────────────
MONGO_INITDB_ROOT_USERNAME=blacknode_user
MONGO_INITDB_ROOT_PASSWORD=Dev123!
MONGO_INITDB_DATABASE=blacknode-sentinel
MONGO_EXTERNAL_PORT=27017

# ── Backend ──────────────────────────────────────────────────
NODE_ENV=production
BACKEND_EXTERNAL_PORT=5004
JWT_SECRET=${JWT_SECRET}
CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# ── Frontend ─────────────────────────────────────────────────
FRONTEND_EXTERNAL_PORT=3000

# ── Optional: ML Engine ──────────────────────────────────────
ML_ENGINE_URL=
ENABLE_ML_DETECTION=false
EOF

success ".env file generated at: $ENV_FILE"

# ── Step 3: Build & Start Services ───────────────────────────
info "Building and starting Docker services..."
echo ""

$COMPOSE_CMD up --build -d --remove-orphans

echo ""

# ── Step 4: Wait for Services to be Healthy ───────────────────
info "Waiting for services to become healthy..."
echo ""

MAX_WAIT=120
INTERVAL=5
ELAPSED=0

check_service() {
    local service=$1
    local container=$2
    local status
    status=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "starting")
    echo "$status"
}

# Wait for MongoDB
info "Waiting for MongoDB..."
while [ $ELAPSED -lt $MAX_WAIT ]; do
    MONGO_STATUS=$(check_service mongodb blacknode-mongodb)
    if [ "$MONGO_STATUS" = "healthy" ]; then
        success "MongoDB is healthy"
        break
    fi
    sleep $INTERVAL
    ELAPSED=$((ELAPSED + INTERVAL))
    printf "  ⏳ MongoDB status: %s (%ds elapsed)\r" "$MONGO_STATUS" "$ELAPSED"
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
    warn "MongoDB health check timed out after ${MAX_WAIT}s. Continuing anyway..."
fi

# Wait for Backend
ELAPSED=0
info "Waiting for Backend..."
while [ $ELAPSED -lt $MAX_WAIT ]; do
    BACKEND_STATUS=$(check_service backend blacknode-backend)
    if [ "$BACKEND_STATUS" = "healthy" ]; then
        success "Backend is healthy"
        break
    fi
    sleep $INTERVAL
    ELAPSED=$((ELAPSED + INTERVAL))
    printf "  ⏳ Backend status: %s (%ds elapsed)\r" "$BACKEND_STATUS" "$ELAPSED"
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
    warn "Backend health check timed out after ${MAX_WAIT}s. Continuing anyway..."
fi

# Wait for Frontend
ELAPSED=0
info "Waiting for Frontend..."
while [ $ELAPSED -lt $MAX_WAIT ]; do
    FRONTEND_STATUS=$(check_service frontend blacknode-frontend)
    if [ "$FRONTEND_STATUS" = "healthy" ]; then
        success "Frontend is healthy"
        break
    fi
    sleep $INTERVAL
    ELAPSED=$((ELAPSED + INTERVAL))
    printf "  ⏳ Frontend status: %s (%ds elapsed)\r" "$FRONTEND_STATUS" "$ELAPSED"
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
    warn "Frontend health check timed out after ${MAX_WAIT}s. Continuing anyway..."
fi

echo ""

# ── Step 5: Display Access Information ────────────────────────
echo -e "${CYAN}"
echo "  ╔═══════════════════════════════════════════════════════╗"
echo "  ║              🚀 Deployment Complete!                 ║"
echo "  ╚═══════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "  ${BOLD}Access URLs:${NC}"
echo -e "    🌐 Frontend:     ${GREEN}http://localhost:3000${NC}"
echo -e "    🔧 Backend API:  ${GREEN}http://localhost:5004${NC}"
echo -e "    📊 Health Check: ${GREEN}http://localhost:5004/health${NC}"
echo ""

echo -e "  ${BOLD}Default Credentials:${NC}"
echo -e "    📧 Email:    ${YELLOW}admin@blacknode.com${NC}"
echo -e "    🔑 Password: ${YELLOW}Admin123!${NC}"
echo ""

echo -e "  ${BOLD}Service Status:${NC}"
$COMPOSE_CMD ps
echo ""

echo -e "  ${BOLD}Useful Commands:${NC}"
echo -e "    📋 View logs:     ${CYAN}$COMPOSE_CMD logs -f${NC}"
echo -e "    📋 Backend logs:  ${CYAN}$COMPOSE_CMD logs -f backend${NC}"
echo -e "    ⏹️  Stop all:      ${CYAN}$COMPOSE_CMD down${NC}"
echo -e "    🔄 Rebuild:       ${CYAN}$COMPOSE_CMD up --build -d${NC}"
echo -e "    🗑️  Full cleanup:  ${CYAN}$COMPOSE_CMD down -v --remove-orphans${NC}"
echo ""
